-- Generated by kit-desk theme ({{ name }}). base16 palette for mini.base16.
return {
  name = "{{ name }}",
  mode = "{{ mode }}",
  base00 = "{{ background }}", base01 = "{{ lighter_background }}", base02 = "{{ selection }}",
  base03 = "{{ muted }}", base04 = "{{ light_foreground }}", base05 = "{{ foreground }}",
  base06 = "{{ bright_foreground }}", base07 = "{{ bright_foreground }}",
  base08 = "{{ red }}", base09 = "{{ orange }}", base0A = "{{ yellow }}", base0B = "{{ green }}",
  base0C = "{{ cyan }}", base0D = "{{ blue }}", base0E = "{{ magenta }}", base0F = "{{ brown }}",
}
