// Generated by kit-desk theme ({{ name }}).
themes {
    work-kit {
        fg "{{ foreground }}"
        bg "{{ selection }}"
        black "{{ background }}"
        red "{{ red }}"
        green "{{ green }}"
        yellow "{{ yellow }}"
        blue "{{ blue }}"
        magenta "{{ magenta }}"
        cyan "{{ cyan }}"
        white "{{ foreground }}"
        orange "{{ orange }}"
    }
}
