"""Targets of kit-models: every harness and kit tool that can use a registered endpoint.

Each target rewrites its own entries from the registry on every sync (idempotent) and removes
entries of endpoints that are gone. Ownership, merge and backup rules: kit_models_files.
Protocol facts and sources: docs/model-endpoints.md of the kit repository.

Route per target and endpoint: "direct" (the harness talks to the endpoint and reads the key
from the environment variable) or "proxy" (the harness talks to the local translating proxy,
which adds key and headers; used when the harness lacks the protocol, cannot reference an
environment variable for the key, or cannot send the custom headers).
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import urllib.parse
from pathlib import Path

import kit_models_files as kf

WRAP_MARK = "# work-kit:managed - kit-models wrapper, regenerated by kit-models sync"
YAML_MARK = "# work-kit:managed - generated by kit-models, do not edit"
PROXY_KEY_VAR = "KIT_MODELS_PROXY_KEY"  # exported by the shell snippet: the local proxy token
OWNER = "33-model-endpoints"
MEETING_SENDS_KEY = True  # 17-meeting-capture sends the local proxy token (env or token file) as Bearer key
TAKEOVER = {"claude", "gemini", "copilot", "meeting"}
RESERVED = {"openai", "anthropic", "azure", "ollama", "google", "gemini", "github-copilot",
            "opencode", "llamacpp", "kit-llm", "claude-subscription", "vscode-lm", "local",
            "chatgpt", "openrouter", "mistral", "groq", "deepseek", "xai", "lmstudio", "api"}


# --- local proxy token ------------------------------------------------------------------------

def proxy_key(app, shell: bool = False) -> str:
    """What a harness sends to the local proxy: the per-install token (app.proxy_token()), not an
    endpoint key. In a shell wrapper (mode 0755) a variable reference instead of the value; the
    wrapper sources the snippet that exports it from the 0600 token file."""
    return "${%s}" % PROXY_KEY_VAR if shell else app.proxy_token()


def protect(ctx, path) -> None:
    """A file that holds the token literally must not be readable by other local users."""
    try:
        if not ctx.dry_run and Path(path).is_file() and Path(path).stat().st_mode & 0o077:
            os.chmod(path, 0o600)
    except OSError:
        pass


# --- route helpers ----------------------------------------------------------------------------

def dyn_headers(ep) -> bool:
    return any("${" in v for v in (ep.get("headers") or {}).values())


def is_loopback(url: str) -> bool:
    return (urllib.parse.urlsplit(url).hostname or "") in ("127.0.0.1", "localhost", "::1")


def openai_base(ep) -> str:
    """OpenAI-compatible base URL ending in /v1 (or whatever the endpoint uses)."""
    base = ep["base_url"].rstrip("/")
    if ep["kind"] == "ollama" and not base.endswith("/v1"):
        base += "/v1"
    return base


def anth_root(ep) -> str:
    base = ep["base_url"].rstrip("/")
    return base[:-3] if base.endswith("/v1") else base


def anth_v1(ep) -> str:
    return anth_root(ep) + "/v1"


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "model"


def env_ref(value: str, style: str) -> str:
    """Rewrite ${VAR} references for a config format."""
    fmt = {"opencode": "{env:\\1}", "pi": "${\\1}", "shell": "${\\1}"}[style]
    return re.sub(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", fmt, value)


def sh_dq(value: str) -> str:
    """Double-quoted shell word that keeps ${VAR} references and escapes everything else."""
    parts = re.split(r"(\$\{[A-Za-z_][A-Za-z0-9_]*\})", value)
    out = []
    for p in parts:
        if re.fullmatch(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}", p):
            out.append(p)
        else:
            out.append(re.sub(r'([\\"$`])', r"\\\1", p))
    return '"' + "".join(out) + '"'


def which(binary: str, home: Path):
    dirs = os.environ.get("PATH", "").split(os.pathsep) + [str(home / ".local/bin")]
    for d in dirs:
        p = Path(d) / binary
        if p.is_file() and os.access(p, os.X_OK):
            return p
    return None


# --- base class -------------------------------------------------------------------------------

class Target:
    name = ""
    label = ""
    binaries: list = []
    protocols = ""      # what it speaks natively (for the matrix)
    mechanism = ""      # how kit-models configures it
    support = "full"    # full | partial | manual

    def __init__(self, app):
        self.app = app
        self.ctx = app.ctx
        self.home = app.home

    def config_dirs(self) -> list:
        return []

    def detected(self) -> bool:
        return any(which(b, self.home) for b in self.binaries) or any(
            Path(d).exists() for d in self.config_dirs())

    def route(self, ep) -> str:
        return "proxy"

    def base_for(self, name, ep, reg, protocol="openai") -> str:
        """Base URL the target uses for this endpoint (proxy or direct)."""
        if self.route(ep) == "proxy":
            b = self.app.proxy_base(name, reg)
            return b + "/v1" if protocol in ("openai", "anthropic-v1") else b
        if protocol == "anthropic":
            return anth_root(ep)
        if protocol == "anthropic-v1":
            return anth_v1(ep)
        return openai_base(ep)

    def sync(self, reg, eps: dict, gone: list) -> None:
        """Write entries for eps {name: ep}; remove entries of endpoints in gone."""

    def show(self, reg, name, ep) -> str:
        return ""


# --- wrappers (claude-<name>, codex-<name>, ...) ----------------------------------------------

def key_helper_path(app) -> Path:
    return app.data / "key-helper"


def write_key_helper(app) -> None:
    kit = app.ctx.bin_dir / "kit-models"
    body = f"""#!/bin/sh
{WRAP_MARK}
# key-helper VAR: print the value of the variable VAR (environment, then
# {app.secrets_file}, then the desktop secret store). key-helper --proxy: make sure the local
# proxy runs and print the local proxy token (from the 0600 token file). Used by harness settings (apiKeyHelper,
# COPILOT_PROVIDER_API_KEY_COMMAND) so that no key is written into a harness config.
if [ "$1" = "--proxy" ]; then
  pid=$(cat "{app.data}/proxy.pid" 2>/dev/null)
  if [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; then "{kit}" proxy start >/dev/null 2>&1; fi
  cat "{app.token_file}"
  exit 0
fi
v=$(printenv "$1")
if [ -z "$v" ] && [ -r "{app.secrets_file}" ]; then v=$(. "{app.secrets_file}" >/dev/null 2>&1; printenv "$1"); fi
if [ -z "$v" ] && command -v secret-tool >/dev/null 2>&1; then
  v=$(secret-tool lookup service work-kit key "$1" 2>/dev/null)
fi
[ -n "$v" ] || {{ echo "key-helper: $1 is not set (kit-models add --new-key)" >&2; exit 1; }}
printf '%s' "$v"
"""
    kf.write_managed_file(app.ctx, key_helper_path(app), body, WRAP_MARK, 0o755)


def wrapper_path(app, harness: str, name: str) -> Path:
    return app.ctx.bin_dir / f"{harness}-{name}"


def write_wrapper(app, harness: str, name: str, lines: list, exec_line: str, proxy: bool) -> None:
    kit = app.ctx.bin_dir / "kit-models"
    body = ["#!/usr/bin/env bash", WRAP_MARK,
            f"# Runs {harness} against the endpoint '{name}' registered with kit-models.",
            f'[ -r "{app.env_file}" ] && . "{app.env_file}"']
    if proxy:
        body.append(f'"{kit}" proxy start >/dev/null || exit 1')
    body += lines + [exec_line]
    kf.write_managed_file(app.ctx, wrapper_path(app, harness, name), "\n".join(body) + "\n",
                          WRAP_MARK, 0o755)


def remove_wrapper(app, harness: str, name: str) -> None:
    kf.remove_managed_file(app.ctx, wrapper_path(app, harness, name), WRAP_MARK)


def headers_block(ep) -> str:
    return "\n".join(f"{k}: {v}" for k, v in (ep.get("headers") or {}).items())


# --- Claude Code ------------------------------------------------------------------------------

class Claude(Target):
    name, label = "claude", "Claude Code"
    binaries = ["claude"]
    protocols = "Anthropic Messages only"
    mechanism = ("wrapper claude-<name> (env + apiKeyHelper via --settings); `default --also claude`: "
                 "~/.claude/settings.json env + apiKeyHelper")

    def cdir(self):
        return Path(os.environ.get("CLAUDE_CONFIG_DIR") or self.home / ".claude")

    def config_dirs(self):
        return [self.cdir()]

    def route(self, ep):
        return "direct" if ep["kind"] == "anthropic" else "proxy"

    def env_for(self, name, ep, reg, model, resolved_headers: bool):
        env = {"ANTHROPIC_BASE_URL": self.base_for(name, ep, reg, "anthropic"),
               "ANTHROPIC_MODEL": model, "ANTHROPIC_DEFAULT_OPUS_MODEL": model,
               "ANTHROPIC_DEFAULT_SONNET_MODEL": model, "ANTHROPIC_DEFAULT_HAIKU_MODEL": model,
               "ANTHROPIC_DEFAULT_FABLE_MODEL": model, "CLAUDE_CODE_SUBAGENT_MODEL": model}
        if ep.get("context_window"):
            env["CLAUDE_CODE_MAX_CONTEXT_TOKENS"] = str(ep["context_window"])
        if self.route(ep) == "direct" and ep.get("headers") and (resolved_headers or not dyn_headers(ep)):
            env["ANTHROPIC_CUSTOM_HEADERS"] = headers_block(ep)
        return env

    def helper(self, ep):
        if self.route(ep) == "proxy" or not ep.get("key_env"):
            return f"{key_helper_path(self.app)} --proxy" if self.route(ep) == "proxy" else None
        return f"{key_helper_path(self.app)} {ep['key_env']}"

    def sync(self, reg, eps, gone):
        for name in gone:
            remove_wrapper(self.app, "claude", name)
        for name, ep in eps.items():
            model = ep["models"][0]
            env = self.env_for(name, ep, reg, model, True)
            lines = [f"export {k}={sh_dq(v)}" for k, v in env.items()]
            helper = self.helper(ep)
            settings = json.dumps({"apiKeyHelper": helper}) if helper else "{}"
            write_wrapper(self.app, "claude", name, lines,
                          f"exec claude --settings {sh_quote(settings)} \"$@\"",
                          self.route(ep) == "proxy")
        self.takeover(reg, eps)

    def takeover(self, reg, eps):
        path = self.cdir() / "settings.json"
        keys = ["ANTHROPIC_BASE_URL", "ANTHROPIC_MODEL", "ANTHROPIC_DEFAULT_OPUS_MODEL",
                "ANTHROPIC_DEFAULT_SONNET_MODEL", "ANTHROPIC_DEFAULT_HAIKU_MODEL",
                "ANTHROPIC_DEFAULT_FABLE_MODEL", "CLAUDE_CODE_SUBAGENT_MODEL",
                "ANTHROPIC_CUSTOM_HEADERS", "CLAUDE_CODE_MAX_CONTEXT_TOKENS"]
        name = reg.get("default")
        want = {("env", k): kf.REMOVE for k in keys}
        want[("apiKeyHelper",)] = kf.REMOVE
        if "claude" in (reg.get("takeover") or []) and name in eps:
            ep = eps[name]
            if ep["kind"] == "anthropic" and dyn_headers(ep):
                ep = dict(ep, kind="openai")  # secret headers: through the proxy
            env = self.env_for(name, ep, reg, reg.get("default_model") or ep["models"][0], False)
            for k, v in env.items():
                want[("env", k)] = v
            h = self.helper(ep)
            if h:
                want[("apiKeyHelper",)] = h
        elif not any(self.ctx.owned(path, k) is not kf.MISSING for k in want):
            return
        kf.json_settings(self.ctx, path, want)

    def show(self, reg, name, ep):
        env = self.env_for(name, ep, reg, ep["models"][0], False)
        lines = [f"export {k}={sh_dq(v)}" for k, v in env.items()]
        h = self.helper(ep)
        return ("\n".join(lines) + (f"\n# ~/.claude/settings.json: \"apiKeyHelper\": \"{h}\"" if h else "")
                + f"\n# or simply run: claude-{name}")


def sh_quote(v: str) -> str:
    return "'" + v.replace("'", "'\"'\"'") + "'"


# --- Codex ------------------------------------------------------------------------------------

class Codex(Target):
    name, label = "codex", "Codex CLI"
    binaries = ["codex"]
    protocols = "OpenAI Responses only (wire_api = \"chat\" was removed)"
    mechanism = ("~/.codex/config.toml [model_providers.<name>] (region); default: model_provider + model "
                 "(region at the top); wrapper codex-<name>")
    TOP = ("# work-kit:begin model-default - managed by kit-models", "# work-kit:end model-default")
    TABLES = ("# work-kit:begin model-providers - managed by kit-models",
              "# work-kit:end model-providers")

    def chome(self):
        return Path(os.environ.get("CODEX_HOME") or self.home / ".codex")

    def config_dirs(self):
        return [self.chome()]

    def route(self, ep):
        return "direct" if ep["kind"] == "openai" and ep.get("responses") else "proxy"

    def table(self, name, ep, reg) -> list:
        lines = [f"[model_providers.{kf.toml_key(name)}]",
                 f"name = {kf.toml_str(name + ' (kit-models)')}",
                 f"base_url = {kf.toml_str(self.base_for(name, ep, reg))}",
                 'wire_api = "responses"']
        if self.route(ep) == "direct":
            if ep.get("key_env"):
                lines.append(f"env_key = {kf.toml_str(ep['key_env'])}")
            static = {k: v for k, v in (ep.get("headers") or {}).items() if "${" not in v}
            envh = {k: re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", v).group(1)
                    for k, v in (ep.get("headers") or {}).items()
                    if re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", v)}
            if static:
                lines.append(f"http_headers = {kf.toml_str(static)}")
            if envh:
                lines.append(f"env_http_headers = {kf.toml_str(envh)}")
        else:  # the local proxy needs its token, exported by the shell snippet
            lines.append(f"env_key = {kf.toml_str(PROXY_KEY_VAR)}")
        return lines

    def sync(self, reg, eps, gone):
        path = self.chome() / "config.toml"
        for name in gone:
            remove_wrapper(self.app, "codex", name)
        body = []
        for name, ep in sorted(eps.items()):
            body += self.table(name, ep, reg) + [""]
            write_wrapper(self.app, "codex", name, [],
                          f"exec codex -c model_provider={sh_quote(name)} -c model={sh_quote(json.dumps(ep['models'][0]))} \"$@\"",
                          self.route(ep) == "proxy")
        if not eps and not path.exists():
            return
        kf.set_region(self.ctx, path, *self.TABLES, "\n".join(body), "end", check_toml=True)
        top = ""
        name = reg.get("default")
        if reg.get("default_explicit") and name in eps:
            old = kf.read(path) if path.exists() else ""
            outside = kf.region_re(*self.TOP).sub("", old)
            head = re.split(r"(?m)^\s*\[", outside, maxsplit=1)[0]
            if re.search(r"(?m)^\s*(model|model_provider)\s*=", head):
                self.ctx.say("keep", path, "model / model_provider are set by you; kit-models default not applied")
            else:
                model = reg.get("default_model") or eps[name]["models"][0]
                top = f"model_provider = {kf.toml_str(name)}\nmodel = {kf.toml_str(model)}"
        kf.set_region(self.ctx, path, *self.TOP, top, "start", check_toml=True)

    def show(self, reg, name, ep):
        return "\n".join(self.table(name, ep, reg)) + f"\n# run: codex-{name}  (or codex -c model_provider={name})"


# --- opencode ---------------------------------------------------------------------------------

class OpenCode(Target):
    name, label = "opencode", "opencode"
    binaries = ["opencode"]
    protocols = "OpenAI chat, OpenAI Responses, Anthropic, Azure (AI SDK packages)"
    mechanism = "opencode.json provider.<name> ({env:VAR} for the key); default: model"

    def cfg(self):
        return Path(os.environ.get("XDG_CONFIG_HOME") or self.home / ".config") / "opencode"

    def config_dirs(self):
        return [self.cfg()]

    def route(self, ep):
        return "proxy" if ep["kind"] == "azure" else "direct"

    def entry(self, name, ep, reg):
        direct = self.route(ep) == "direct"
        anth = ep["kind"] == "anthropic"
        opts = {"baseURL": self.base_for(name, ep, reg, "anthropic-v1" if anth else "openai")}
        if direct and ep.get("key_env"):
            opts["apiKey"] = "{env:%s}" % ep["key_env"]
        elif not direct:
            opts["apiKey"] = proxy_key(self.app)
        if direct and ep.get("headers"):
            opts["headers"] = {k: env_ref(v, "opencode") for k, v in ep["headers"].items()}
        return {"npm": "@ai-sdk/anthropic" if anth and direct else "@ai-sdk/openai-compatible",
                "name": f"{name} (kit-models)", "options": opts,
                "models": {m: dict({"name": m}, **({"limit": {"context": ep["context_window"],
                                                                "output": min(16384, ep["context_window"] // 4)}}
                                                     if ep.get("context_window") else {}))
                           for m in ep["models"]}}

    def sync(self, reg, eps, gone):
        path = self.cfg() / "opencode.json"
        if (self.cfg() / "opencode.jsonc").exists() and not path.exists():
            if eps:
                self.ctx.say("note", self.cfg() / "opencode.jsonc",
                             "kit-models writes opencode.json; add the provider by hand: kit-models show <name> --target opencode")
            return
        want = {("provider", n): kf.REMOVE for n in gone}
        for n, ep in eps.items():
            want[("provider", n)] = self.entry(n, ep, reg)
        name = reg.get("default")
        if reg.get("default_explicit") and name in eps:
            want[("model",)] = f"{name}/{reg.get('default_model') or eps[name]['models'][0]}"
        elif self.ctx.owned(path, ("model",)) is not kf.MISSING:
            want[("model",)] = kf.REMOVE
        if not eps and not any(self.ctx.owned(path, k) is not kf.MISSING for k in want):
            return
        kf.json_settings(self.ctx, path, want)
        protect(self.ctx, path)

    def show(self, reg, name, ep):
        return json.dumps({"provider": {name: self.entry(name, ep, reg)},
                           "model": f"{name}/{ep['models'][0]}"}, indent=2)


# --- pi ---------------------------------------------------------------------------------------

class Pi(Target):
    name, label = "pi", "pi coding agent"
    binaries = ["pi"]
    protocols = "OpenAI chat, OpenAI Responses, Anthropic, Azure Responses, Gemini"
    mechanism = ("~/.pi/agent/models.json providers.<name> (\"$VAR\" key); default: settings.json "
                 "defaultProvider/defaultModel. With 70-workbench installed, wb-state writes the provider")

    def pdir(self):
        return Path(os.environ.get("PI_CODING_AGENT_DIR") or self.home / ".pi/agent")

    def config_dirs(self):
        return [self.pdir()]

    def route(self, ep):
        return "proxy" if ep["kind"] == "azure" else "direct"

    def entry(self, name, ep, reg):
        direct = self.route(ep) == "direct"
        anth = ep["kind"] == "anthropic"
        e = {"baseUrl": self.base_for(name, ep, reg, "anthropic" if anth else "openai"),
             "api": "anthropic-messages" if anth and direct else "openai-completions",
             "apiKey": ("$" + ep["key_env"]) if direct and ep.get("key_env") else proxy_key(self.app),
             "models": [dict({"id": m, "name": m}, **({"contextWindow": ep["context_window"]}
                                                     if ep.get("context_window") else {}))
                        for m in ep["models"]]}
        if direct and ep.get("headers"):
            e["headers"] = {k: env_ref(v, "pi") for k, v in ep["headers"].items()}
        return e

    def sync(self, reg, eps, gone):
        path = self.pdir() / "models.json"
        if Workbench(self.app).detected():
            if eps:
                self.ctx.say("note", path, "provider entries are written by 70-workbench (wb-state)")
            eps = {}
            gone = list(gone) + [n for n in reg["endpoints"]]
        want = {("providers", n): kf.REMOVE for n in gone}
        for n, ep in eps.items():
            want[("providers", n)] = self.entry(n, ep, reg)
        if eps or any(self.ctx.owned(path, k) is not kf.MISSING for k in want):
            kf.json_settings(self.ctx, path, want)
            protect(self.ctx, path)
        spath = self.pdir() / "settings.json"
        name = reg.get("default")
        sw = {("defaultProvider",): kf.REMOVE, ("defaultModel",): kf.REMOVE}
        if reg.get("default_explicit") and name in reg["endpoints"] and self.detected():
            sw = {("defaultProvider",): name,
                  ("defaultModel",): reg.get("default_model") or reg["endpoints"][name]["models"][0]}
        elif not any(self.ctx.owned(spath, k) is not kf.MISSING for k in sw):
            return
        kf.json_settings(self.ctx, spath, sw)

    def show(self, reg, name, ep):
        return json.dumps({"providers": {name: self.entry(name, ep, reg)}}, indent=2)


# --- Copilot CLI ------------------------------------------------------------------------------

class CopilotCli(Target):
    name, label = "copilot", "GitHub Copilot CLI (BYOK)"
    binaries = ["copilot"]
    protocols = "OpenAI chat or Responses, Azure, Anthropic (COPILOT_PROVIDER_* env vars)"
    mechanism = ("wrapper copilot-<name> (env vars, key via COPILOT_PROVIDER_API_KEY_COMMAND); "
                 "`default --also copilot`: exported by the shell snippet")

    def config_dirs(self):
        return [Path(os.environ.get("COPILOT_HOME") or self.home / ".copilot")]

    def route(self, ep):
        return "direct"

    def env_for(self, name, ep, reg) -> dict:
        kind = {"ollama": "openai"}.get(ep["kind"], ep["kind"])
        base = {"anthropic": anth_root(ep), "azure": ep["base_url"].rstrip("/")}.get(kind, openai_base(ep))
        env = {"COPILOT_PROVIDER_TYPE": kind, "COPILOT_PROVIDER_BASE_URL": base,
               "COPILOT_MODEL": ep["models"][0]}
        if ep.get("key_env"):
            env["COPILOT_PROVIDER_API_KEY_COMMAND"] = f"{key_helper_path(self.app)} {ep['key_env']}"
        if kind == "azure":
            env["COPILOT_PROVIDER_AZURE_API_VERSION"] = ep.get("api_version") or ""
            env["COPILOT_PROVIDER_WIRE_MODEL"] = ep["models"][0]
        if ep.get("headers"):
            env["COPILOT_PROVIDER_HEADERS"] = headers_block(ep)
        return env

    def sync(self, reg, eps, gone):
        for name in gone:
            remove_wrapper(self.app, "copilot", name)
        for name, ep in eps.items():
            lines = [f"export {k}={sh_dq(v)}" for k, v in self.env_for(name, ep, reg).items()]
            write_wrapper(self.app, "copilot", name, lines, 'exec copilot "$@"', False)

    def show(self, reg, name, ep):
        return "\n".join(f"export {k}={sh_dq(v)}" for k, v in self.env_for(name, ep, reg).items())


# --- Gemini CLI -------------------------------------------------------------------------------

class Gemini(Target):
    name, label = "gemini", "Gemini CLI"
    binaries = ["gemini"]
    protocols = "Gemini API only"
    mechanism = ("always through the proxy: wrapper gemini-<name> and settings.json "
                 "security.auth.selectedType = gemini-api-key (if unset); `default --also gemini`: "
                 "~/.gemini/.env region")
    BEGIN, END = "# work-kit:begin model-endpoint - managed by kit-models", "# work-kit:end model-endpoint"

    def config_dirs(self):
        return [self.home / ".gemini"]

    def env_for(self, name, reg, model, shell: bool = False):
        return {"GOOGLE_GEMINI_BASE_URL": self.app.proxy_base(name, reg),
                "GEMINI_API_KEY": proxy_key(self.app, shell), "GEMINI_MODEL": model}

    def sync(self, reg, eps, gone):
        for name in gone:
            remove_wrapper(self.app, "gemini", name)
        for name, ep in eps.items():
            lines = [f"export {k}={sh_dq(v)}" for k, v in self.env_for(name, reg, ep["models"][0], True).items()]
            write_wrapper(self.app, "gemini", name, lines, 'exec gemini "$@"', True)
        envf = self.home / ".gemini/.env"
        spath = self.home / ".gemini/settings.json"
        key = ("security", "auth", "selectedType")
        # Gemini CLI 0.61 treats GOOGLE_GEMINI_BASE_URL without a selected auth type as
        # "gateway" and refuses to start headless; gemini-api-key makes the base URL apply.
        # A type you selected yourself (e.g. a Google login) is kept; the wrappers then fail.
        if eps:
            kf.json_settings(self.ctx, spath, {key: "gemini-api-key"})
        elif self.ctx.owned(spath, key) is not kf.MISSING:
            kf.json_settings(self.ctx, spath, {key: kf.REMOVE})
        name = reg.get("default")
        if "gemini" in (reg.get("takeover") or []) and name in eps:
            env = self.env_for(name, reg, reg.get("default_model") or eps[name]["models"][0])
            kf.set_region(self.ctx, envf, self.BEGIN, self.END,
                          "\n".join(f"{k}={v}" for k, v in env.items()))
            protect(self.ctx, envf)
        elif envf.exists():
            kf.set_region(self.ctx, envf, self.BEGIN, self.END, "")

    def show(self, reg, name, ep):
        return ("# needs the proxy: kit-models proxy start\n"
                + "\n".join(f"export {k}={v}" for k, v in self.env_for(name, reg, ep["models"][0]).items()))


# --- VS Code Copilot Chat BYOK ----------------------------------------------------------------

class VSCode(Target):
    name, label = "vscode", "VS Code Copilot Chat (BYOK)"
    binaries = ["code"]
    protocols = "OpenAI chat or Responses, Anthropic Messages, Azure"
    mechanism = ("<VS Code user dir>/chatLanguageModels.json, one 'customendpoint' provider "
                 "'kit: <name>'; the key is asked once by VS Code (${input:...}, secret storage)")

    def user_dirs(self, existing=True):
        xdg = Path(os.environ.get("XDG_CONFIG_HOME") or self.home / ".config")
        dirs = [xdg / "Code/User", self.home / "Library/Application Support/Code/User"]
        return [d for d in dirs if d.parent.exists()] if existing else dirs

    def config_dirs(self):
        return [d.parent for d in self.user_dirs(False)]

    def route(self, ep):
        return "proxy" if dyn_headers(ep) else "direct"

    def entry(self, name, ep, reg):
        direct = self.route(ep) == "direct"
        models = []
        for m in ep["models"]:
            if not direct:
                url, api = self.app.proxy_base(name, reg) + "/v1/chat/completions", "chat-completions"
            elif ep["kind"] == "anthropic":
                url, api = anth_v1(ep) + "/messages", "messages"
            elif ep["kind"] == "azure":
                url = (ep["base_url"].rstrip("/") + f"/openai/deployments/{m}/chat/completions"
                       f"?api-version={ep.get('api_version') or '2024-10-21'}")
                api = "chat-completions"
            else:
                url, api = openai_base(ep) + "/chat/completions", "chat-completions"
            ctx_w = ep.get("context_window") or 108192
            e = {"id": m, "name": f"{m} ({name})", "url": url, "apiType": api, "toolCalling": True,
                 "vision": False, "maxInputTokens": max(1024, ctx_w - min(8192, ctx_w // 4)),
                 "maxOutputTokens": min(8192, ctx_w // 4)}
            if direct and ep.get("headers"):
                e["requestHeaders"] = dict(ep["headers"])
            if direct and ep["kind"] == "azure":
                e["requestHeaders"] = dict(e.get("requestHeaders") or {}, **{"api-key": "${apiKey}"})
            models.append(e)
        prov = {"name": f"kit: {name}", "vendor": "customendpoint", "models": models}
        if direct and ep.get("key_env"):
            prov["apiKey"] = "${input:kit-%s-key}" % name
        else:
            prov["apiKey"] = proxy_key(self.app)
        return prov

    def sync(self, reg, eps, gone):
        entries = {f"kit: {n}": self.entry(n, ep, reg) for n, ep in eps.items()}
        for d in self.user_dirs():
            json_list_sync(self.ctx, d / "chatLanguageModels.json", None, "name", entries,
                           [f"kit: {n}" for n in gone])
            protect(self.ctx, d / "chatLanguageModels.json")

    def show(self, reg, name, ep):
        return json.dumps([self.entry(name, ep, reg)], indent=2)


def json_list_sync(ctx, path: Path, list_key, id_field: str, entries: dict, gone_ids: list):
    """Upsert entries {id: obj} into a JSON list (the file itself, or data[list_key]) and drop
    gone ids, only where the current object is still the one kit-models wrote last time."""
    exists = path.exists()
    if not exists and not entries:
        return
    text = kf.read(path) if exists else ""
    try:
        data = json.loads(text) if text.strip() else ([] if list_key is None else {})
    except ValueError:
        try:
            json.loads(kf.strip_jsonc(text))
            ctx.say("skip", path, "has comments; add the entries by hand (kit-models show <name>)")
        except ValueError:
            ctx.say("skip", path, "not valid JSON; left untouched")
        return
    lst = data if list_key is None else data.setdefault(list_key, [])
    if not isinstance(lst, list):
        ctx.say("skip", path, "unexpected shape; left untouched")
        return
    before = json.dumps(data, sort_keys=True)
    index = {x.get(id_field): i for i, x in enumerate(lst) if isinstance(x, dict)}
    for eid in list(gone_ids) + [k for k in entries]:
        pass
    for eid in gone_ids:
        if eid in entries:
            continue
        owned = ctx.owned(path, ("#list", eid))
        if eid in index and owned is not kf.MISSING and lst[index[eid]] == owned:
            lst[index[eid]] = None
        ctx.disown(path, ("#list", eid))
    for eid, obj in entries.items():
        owned = ctx.owned(path, ("#list", eid))
        if eid in index:
            cur = lst[index[eid]]
            if cur == obj:
                ctx.own(path, ("#list", eid), obj)
            elif owned is not kf.MISSING and cur == owned:
                lst[index[eid]] = obj
                ctx.own(path, ("#list", eid), obj)
            else:
                ctx.disown(path, ("#list", eid))
                ctx.say("keep", path, f"'{eid}' was changed by you; kit-models entry not applied")
        else:
            lst.append(obj)
            ctx.own(path, ("#list", eid), obj)
    lst[:] = [x for x in lst if x is not None]
    if json.dumps(data, sort_keys=True) == before:
        if exists:
            ctx.say("unchanged", path)
        return
    if exists:
        ctx.backup(path)
    ctx.write_text(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    ctx.say("update" if exists else "create", path)


# --- Aider ------------------------------------------------------------------------------------

class Aider(Target):
    name, label = "aider", "Aider"
    binaries = ["aider"]
    protocols = "OpenAI chat, Azure, Anthropic (litellm)"
    mechanism = ("wrapper aider-<name> (direct for OpenAI-compatible without headers, else proxy); "
                 "default: ~/.aider.conf.yml region (through the proxy: the file cannot reference a variable)")
    BEGIN, END = "# work-kit:begin model-endpoint - managed by kit-models", "# work-kit:end model-endpoint"

    def config_dirs(self):
        return [self.home / ".aider"]

    def route(self, ep):
        return "direct" if ep["kind"] in ("openai", "ollama") and not ep.get("headers") else "proxy"

    def sync(self, reg, eps, gone):
        for name in gone:
            remove_wrapper(self.app, "aider", name)
        for name, ep in eps.items():
            m = ep["models"][0]
            # AIDER_* variables win over ~/.aider.conf.yml (a default set there); plain
            # OPENAI_API_BASE would not.
            if self.route(ep) == "direct":
                lines = [f"export AIDER_OPENAI_API_BASE={sh_dq(openai_base(ep))}"]
                if ep.get("key_env"):
                    lines.append(f'export AIDER_OPENAI_API_KEY="${{{ep["key_env"]}:-}}"')
                else:
                    lines.append("export AIDER_OPENAI_API_KEY=none")
            else:
                lines = [f"export AIDER_OPENAI_API_BASE={sh_dq(self.base_for(name, ep, reg))}",
                         f'export AIDER_OPENAI_API_KEY="{proxy_key(self.app, True)}"']
            lines.append(f"export AIDER_MODEL={sh_quote('openai/' + m)}")
            write_wrapper(self.app, "aider", name, lines,
                          'exec aider "$@"', self.route(ep) == "proxy")
        path = self.home / ".aider.conf.yml"
        name = reg.get("default")
        body = ""
        if reg.get("default_explicit") and name in eps:
            old = kf.read(path) if path.exists() else ""
            user = kf.region_re(self.BEGIN, self.END).sub("", old)
            taken = set(re.findall(r"(?m)^([A-Za-z0-9_-]+)\s*:", user)) & {"model", "openai-api-base", "openai-api-key"}
            if taken:
                self.ctx.say("keep", path, f"{', '.join(sorted(taken))} set by you; kit-models default not applied")
            else:
                model = reg.get("default_model") or eps[name]["models"][0]
                body = (f"model: {kf.yaml_str('openai/' + model)}\n"
                        f"openai-api-base: {kf.yaml_str(self.app.proxy_base(name, reg) + '/v1')}\n"
                        f"openai-api-key: {proxy_key(self.app)}")
        if body or path.exists():
            kf.set_region(self.ctx, path, self.BEGIN, self.END, body)
            protect(self.ctx, path)

    def show(self, reg, name, ep):
        return (f"# run: aider-{name}\n# or ~/.aider.conf.yml (proxy running):\n"
                f"model: openai/{ep['models'][0]}\nopenai-api-base: {self.app.proxy_base(name, reg)}/v1\n"
                f"openai-api-key: {proxy_key(self.app)}")


# --- Continue ---------------------------------------------------------------------------------

class Continue(Target):
    name, label = "continue", "Continue (VS Code / JetBrains / cn)"
    binaries = ["cn"]
    protocols = "OpenAI, Azure, Anthropic, Ollama"
    mechanism = ("~/.continue/config.yaml models (region), through the proxy: the IDE extensions "
                 "cannot read shell variables")
    BEGIN, END = "# work-kit:begin model-endpoints - managed by kit-models", "# work-kit:end model-endpoints"

    def config_dirs(self):
        return [self.home / ".continue"]

    def items(self, reg, eps, indent: str) -> str:
        out = []
        for name, ep in sorted(eps.items()):
            for m in ep["models"]:
                out += [f"{indent}- name: {kf.yaml_str(m + ' (' + name + ')')}",
                        f"{indent}  provider: openai",
                        f"{indent}  model: {kf.yaml_str(m)}",
                        f"{indent}  apiBase: {kf.yaml_str(self.app.proxy_base(name, reg) + '/v1')}",
                        f"{indent}  apiKey: {proxy_key(self.app)}",
                        f"{indent}  roles: [chat, edit, apply]"]
        return "\n".join(out)

    def sync(self, reg, eps, gone):
        self._sync(reg, eps, gone)
        protect(self.ctx, self.home / ".continue/config.yaml")

    def _sync(self, reg, eps, gone):
        path = self.home / ".continue/config.yaml"
        if not path.exists():
            if not eps:
                return
            body = self.items(reg, eps, "  ")
            text = (f"name: Local config\nversion: 1.0.0\nschema: v1\nmodels:\n"
                    f"{self.BEGIN}\n{body}\n{self.END}\n")
            self.ctx.write_text(path, text)
            self.ctx.say("create", path)
            return
        old = kf.read(path)
        rx = kf.region_re(self.BEGIN, self.END)
        if rx.search(old):
            m = re.search(r"(?m)^([ \t]*)- name:", rx.search(old).group(0))
            indent = m.group(1) if m else "  "
            kf.set_region(self.ctx, path, self.BEGIN, self.END, self.items(reg, eps, indent))
            return
        if not eps:
            return
        mm = re.search(r"(?m)^models:[ \t]*\n", old)
        if re.search(r"(?m)^models:[ \t]*\S", old):
            self.ctx.say("skip", path, "'models:' uses flow style; add the entries by hand (kit-models show)")
            return
        if mm:
            nxt = re.match(r"([ \t]*)-", old[mm.end():])
            indent = nxt.group(1) if nxt else "  "
            new = old[:mm.end()] + f"{self.BEGIN}\n{self.items(reg, eps, indent)}\n{self.END}\n" + old[mm.end():]
        else:
            new = old.rstrip("\n") + f"\nmodels:\n{self.BEGIN}\n{self.items(reg, eps, '  ')}\n{self.END}\n"
        kf.replace_text(self.ctx, path, old, new)

    def show(self, reg, name, ep):
        return "models:\n" + self.items(reg, {name: ep}, "  ")


# --- Cursor (manual) --------------------------------------------------------------------------

class Cursor(Target):
    name, label = "cursor", "Cursor"
    binaries = ["cursor", "cursor-agent"]
    protocols = "OpenAI key + 'Override OpenAI Base URL' (settings screen only)"
    mechanism = "none: no documented config file; `kit-models show <name> --target cursor` prints the values"
    support = "manual"

    def config_dirs(self):
        return [self.home / ".cursor"]

    def route(self, ep):
        return "manual"

    def show(self, reg, name, ep):
        return ("Cursor Settings > Models > OpenAI API Key: the key of the endpoint "
                f"(kit-models env; variable {ep.get('key_env')}),\n"
                f"'Override OpenAI Base URL': {openai_base(ep)}, then add the model names: "
                f"{', '.join(ep['models'])}.\n"
                "Cursor may send the requests from its own servers: the endpoint then has to be "
                "reachable from the internet, and a local proxy does not help. Ask IT first.")


# --- 70-workbench -----------------------------------------------------------------------------

class Workbench(Target):
    name, label = "workbench", "70-workbench registry (pi workers)"
    binaries = ["wb-state"]
    protocols = "via pi: OpenAI chat, Anthropic"
    mechanism = f"wb-state models add-provider --owner {OWNER} (pi workers: pi-worker <n> <name>/<model>)"

    def wb(self):
        return os.environ.get("WB_STATE") or (str(which("wb-state", self.home) or ""))

    def detected(self):
        return bool(self.wb())

    def route(self, ep):
        return "proxy" if ep["kind"] == "azure" or ep.get("headers") else "direct"

    def args(self, name, ep, reg):
        if self.route(ep) == "proxy":
            kind, base, key = "openai", self.app.proxy_base(name, reg) + "/v1", PROXY_KEY_VAR
        else:
            kind = "anthropic" if ep["kind"] == "anthropic" else "openai"
            base = anth_root(ep) if kind == "anthropic" else openai_base(ep)
            key = ep.get("key_env")
            if is_loopback(base):
                kind = "local" if kind == "openai" else kind
        a = ["models", "add-provider", "--id", name, "--kind", kind, "--base-url", base,
             "--label", f"{name} (kit-models)", "--owner", OWNER]
        if key:
            a += ["--key-env", key]
        if ep.get("context_window"):
            a += ["--context-window", str(ep["context_window"])]
        for m in ep["models"]:
            a += ["--model", m]
        return a

    def run(self, args):
        if self.ctx.dry_run:
            self.ctx.say("would run", "wb-state " + " ".join(args))
            return
        try:
            r = subprocess.run([self.wb(), *args], capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.TimeoutExpired) as e:
            self.ctx.say("skip", "wb-state", f"failed: {e}")
            return
        out = (r.stdout + r.stderr).strip().splitlines()
        self.ctx.say("update" if r.returncode == 0 else "skip", "wb-state " + " ".join(args[:4]),
                     out[-1] if out else f"exit {r.returncode}")

    def sync(self, reg, eps, gone):
        if not self.wb():
            if eps:
                self.ctx.say("skip", "workbench", "wb-state not found (install 70-workbench, or set WB_STATE)")
            return
        for name in gone:
            self.run(["models", "remove-provider", "--id", name, "--owner", OWNER])
        for name, ep in eps.items():
            self.run(self.args(name, ep, reg))

    def show(self, reg, name, ep):
        return "wb-state " + " ".join(sh_quote(a) if " " in a else a for a in self.args(name, ep, reg))


# --- 72-vscode-workbench ----------------------------------------------------------------------

class VSCodeWorkbench(Target):
    name, label = "vscode-workbench", "72-vscode-workbench registry"
    protocols = "OpenAI chat with Bearer key (harness 'api')"
    mechanism = "~/.config/work-kit/workbench/models.json providers + models (harness api)"

    def reg_file(self):
        return self.ctx.conf_dir / "workbench/models.json"

    def detected(self):
        if self.reg_file().exists():
            return True
        for d in (self.home / ".vscode/extensions", self.home / ".vscode-server/extensions"):
            if d.is_dir() and any(p.name.startswith("work-kit.kit-workbench") for p in d.iterdir()):
                return True
        return False

    def route(self, ep):
        return "direct" if ep["kind"] in ("openai", "ollama") and not ep.get("headers") else "proxy"

    def entries(self, name, ep, reg):
        direct = self.route(ep) == "direct"
        base = openai_base(ep) if direct else self.app.proxy_base(name, reg) + "/v1"
        prov = {"id": name, "label": f"{name} (kit-models)",
                "kind": "local" if direct and is_loopback(base) else "cloud",
                "baseUrl": base, "api": "openai",
                "apiKeyEnv": (ep.get("key_env") if direct else "KIT_MODELS_PROXY_KEY"),
                "dataStaysLocal": bool(direct and is_loopback(base)), "managedBy": "kit-models"}
        if prov["apiKeyEnv"] is None:
            del prov["apiKeyEnv"]
        models = {f"{name}-{slug(m)}": {"id": f"{name}-{slug(m)}", "label": f"{m} ({name})",
                                        "harness": "api", "provider": name, "modelRef": m,
                                        "roles": ["worker", "orchestrator"], "enabled": True,
                                        **({"contextWindow": ep["context_window"]}
                                           if ep.get("context_window") else {}),
                                        "notes": "registered by kit-models; data classes: "
                                                 + ", ".join(ep.get("data_classes") or ["PUBLIC"])}
                  for m in ep["models"]}
        return prov, models

    def sync(self, reg, eps, gone):
        path = self.reg_file()
        provs, models = {}, {}
        for n, ep in eps.items():
            p, ms = self.entries(n, ep, reg)
            provs[n] = p
            models.update(ms)
        gone_models = [k[1] for k in self.ctx.owned_keys(path, ("#list",)) if k[1] not in models
                       and k[1] not in provs]
        if not path.exists() and not eps:
            return
        if not path.exists():
            self.ctx.write_text(path, json.dumps({"version": 1, "providers": [], "harnesses": [],
                                                  "models": []}, indent=2) + "\n")
        json_list_sync(self.ctx, path, "providers", "id", provs, list(gone))
        json_list_sync(self.ctx, path, "models", "id", models, gone_models)

    def show(self, reg, name, ep):
        p, ms = self.entries(name, ep, reg)
        return json.dumps({"providers": [p], "models": list(ms.values())}, indent=2)


# --- evalkit, llm-usage, meeting, doc-qa ------------------------------------------------------

class Evalkit(Target):
    name, label = "evalkit", "50-eval evalkit"
    binaries = ["evalkit"]
    protocols = "OpenAI chat (type: openai, key from api_key_env)"
    mechanism = "~/.config/work-kit/evalkit/kit-models-providers.yaml: provider entries to copy into suites"

    def route(self, ep):
        return "direct" if ep["kind"] in ("openai", "ollama") and not ep.get("headers") else "proxy"

    def items(self, reg, eps):
        out = []
        for name, ep in sorted(eps.items()):
            direct = self.route(ep) == "direct"
            for m in ep["models"]:
                out += [f"  - id: {kf.yaml_str(name + '-' + slug(m))}", "    type: openai",
                        f"    base_url: {kf.yaml_str(openai_base(ep) if direct else self.app.proxy_base(name, reg) + '/v1')}",
                        f"    model: {kf.yaml_str(m)}"]
                if direct and ep.get("key_env"):
                    out.append(f"    api_key_env: {ep['key_env']}")
                elif not direct:
                    out.append(f"    api_key_env: {PROXY_KEY_VAR}  # the local proxy token")
                out.append(f"    # data classes: {', '.join(ep.get('data_classes') or ['PUBLIC'])}"
                           + ("" if direct else "; needs: kit-models proxy start"))
        return "\n".join(out)

    def sync(self, reg, eps, gone):
        path = self.ctx.conf_dir / "evalkit/kit-models-providers.yaml"
        if not eps:
            kf.remove_managed_file(self.ctx, path, YAML_MARK)
            return
        body = (f"{YAML_MARK}\n# Copy the entries you need into the providers: list of a suite.\n"
                f"providers:\n{self.items(reg, eps)}\n")
        kf.write_managed_file(self.ctx, path, body, YAML_MARK)

    def show(self, reg, name, ep):
        return "providers:\n" + self.items(reg, {name: ep})


class LlmUsage(Target):
    name, label = "llm-usage", "14-llm-usage proxy"
    binaries = ["llm-usage"]
    protocols = "OpenAI-compatible pass-through"
    mechanism = ("shell snippet exports LLM_USAGE_UPSTREAM = the proxy URL of the default endpoint "
                 "(llm-usage start then logs calls to it)")

    def env(self, reg):
        name = reg.get("default")
        if name in reg["endpoints"] and self.detected():
            return {"LLM_USAGE_UPSTREAM": self.app.proxy_base(name, reg) + "/v1"}
        return {}

    def show(self, reg, name, ep):
        return (f"kit-models proxy start\nllm-usage start --upstream {self.app.proxy_base(name, reg)}/v1 "
                f"--provider {name}\nexport OPENAI_BASE_URL=http://127.0.0.1:4011/v1\n"
                f"export OPENAI_API_KEY=\"${PROXY_KEY_VAR}\"  # llm-usage passes the client key on; the "
                "proxy needs its local token")


class Meeting(Target):
    name, label = "meeting", "17-meeting-capture summaries"
    binaries = ["meeting"]
    protocols = "OpenAI chat, Bearer key sent to the local proxy (loopback only)"
    mechanism = ("opt-in: `default <name> --also meeting` writes summary_url (proxy) and summary_model "
                 "into meeting.conf; the endpoint must be allowed INTERNAL data or more. meeting finds the "
                 "local proxy token itself")
    support = "partial"
    BEGIN, END = "# work-kit:begin model-endpoint - managed by kit-models", "# work-kit:end model-endpoint"

    def sync(self, reg, eps, gone):
        path = self.ctx.conf_dir / "meeting.conf"
        name = reg.get("default")
        body = ""
        if "meeting" in (reg.get("takeover") or []) and name in eps:
            ep = eps[name]
            classes = set(ep.get("data_classes") or [])
            old = kf.read(path) if path.exists() else ""
            user = kf.region_re(self.BEGIN, self.END).sub("", old)
            if not classes & {"INTERNAL", "CONFIDENTIAL", "CUSTOMER"}:
                self.ctx.say("skip", path, f"'{name}' is allowed PUBLIC data only; meeting transcripts "
                             "are at least INTERNAL. Not configured")
            elif not MEETING_SENDS_KEY:
                self.ctx.say("skip", path, "meeting sends no key with its summary request, and the local "
                             "proxy refuses requests without its token. Not configured until "
                             "17-meeting-capture can send one")
            elif re.search(r"(?m)^\s*summary_(url|model)\s*=", user):
                self.ctx.say("keep", path, "summary_url/summary_model set by you; not changed")
            else:
                model = reg.get("default_model") or ep["models"][0]
                body = (f"# endpoint '{name}' via the local kit-models proxy. The meeting AI policy "
                        f"must allow this model (IT approval).\n"
                        f"summary_url={self.app.proxy_base(name, reg)}/v1\nsummary_model={model}")
                self.ctx.say("note", path, "summaries go to a company model now: check "
                             "meeting-ai-policy.md and the consent of the participants")
        if body or path.exists():
            kf.set_region(self.ctx, path, self.BEGIN, self.END, body)

    def show(self, reg, name, ep):
        return (f"# ~/.config/work-kit/meeting.conf (only if the meeting AI policy allows it)\n"
                f"# meeting sends the local proxy token by itself (${PROXY_KEY_VAR} or the token file)\n"
                f"summary_url={self.app.proxy_base(name, reg)}/v1\nsummary_model={ep['models'][0]}")


class DocQa(Target):
    name, label = "doc-qa", "18-doc-qa prompts"
    binaries = ["doc-qa"]
    protocols = "none (prints a prompt)"
    mechanism = "nothing to write: doc-qa ask \"...\" --prompt | kit-models ask --name <name> -"
    support = "partial"

    def route(self, ep):
        return "direct"

    def show(self, reg, name, ep):
        return f'doc-qa ask "<question>" --prompt | kit-models ask --name {name} -'


TARGETS = [Claude, Codex, OpenCode, Gemini, CopilotCli, VSCode, Aider, Pi, Continue, Cursor,
           Workbench, VSCodeWorkbench, Evalkit, LlmUsage, Meeting, DocQa]
BY_NAME = {t.name: t for t in TARGETS}


# --- driver -----------------------------------------------------------------------------------

def applies(t: Target, ep: dict) -> bool:
    sel = ep.get("targets")
    if sel == ["all"]:
        return True
    if sel:
        return t.name in sel
    return t.detected()


def sync_all(app, reg: dict, only=None) -> None:
    """Rewrite every target from the registry; drop entries of endpoints that are gone."""
    ctx = app.ctx
    write_key_helper(app)
    known = ctx.state.setdefault("targets", {})
    for cls in TARGETS:
        if only and cls.name not in only:
            continue
        t = cls(app)
        eps = {n: ep for n, ep in reg["endpoints"].items() if applies(t, ep)}
        before = set(known.get(t.name) or [])
        gone = sorted(before - set(eps))
        if not eps and not gone and t.name not in ("claude", "gemini", "meeting", "pi", "codex",
                                                   "opencode", "aider"):
            continue
        try:
            t.sync(reg, eps, gone)
        except OSError as e:
            ctx.say("skip", t.label, f"{e.__class__.__name__}: {e}")
            continue
        if sorted(eps) != sorted(before):
            known[t.name] = sorted(eps)
            ctx.state_dirty = True
    extra = {}
    for n in ("llm-usage",):
        extra.update(BY_NAME[n](app).env(reg))
    app.extra_env = extra


def remove_all(app, reg: dict, name: str) -> None:
    """Called before the endpoint leaves the registry; sync_all afterwards removes it."""


def uses_proxy(app, reg: dict) -> bool:
    for n, ep in reg["endpoints"].items():
        for cls in TARGETS:
            t = cls(app)
            if cls.name in ("cursor", "doc-qa", "llm-usage"):
                continue
            if applies(t, ep) and t.route(ep) == "proxy" and cls.name not in ("gemini",):
                return True
        if "gemini" in (reg.get("takeover") or []) or "meeting" in (reg.get("takeover") or []):
            return True
    return False


def matrix(app) -> str:
    rows = ["target            detected  support  native protocols / mechanism"]
    for cls in TARGETS:
        t = cls(app)
        rows.append(f"{t.name:17} {'yes' if t.detected() else 'no':9} {t.support:8} {t.protocols}")
        rows.append(f"{'':37}{t.mechanism}")
    return "\n".join(rows)


def show(app, reg: dict, name: str, target=None) -> str:
    ep = reg["endpoints"][name]
    out = []
    for cls in TARGETS:
        if target and cls.name != target:
            continue
        t = cls(app)
        text = t.show(reg, name, ep)
        if text:
            route = t.route(ep)
            out.append(f"== {t.label} ({t.name}; route: {route})\n{text}")
    if target and not out:
        raise SystemExit(f"kit-models: unknown target '{target}'")
    return "\n\n".join(out)
